diamonds <- read.csv("/Users/malit/Downloads/archive (1)/diamonds.csv")
data("diamonds")
data("diamonds")
View(diamonds)
mutate(diamonds,carat_2=carat*200)
install.packages("tidyverse")
library(tidyverse)
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point()
ggplot(data = diamonds,aes(x=carat, y=price))
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point()
diamonds <- read.csv("/Users/malit/Downloads/archive (1)/diamonds.csv")
ggplot(data = diamonds,aes(x=carat, y=price))

plot(x=diamonds$carat,y=diamonds$price)
plot(x=diamonds$carat,y=diamonds$price,main=DIAMONDS)
plot(x=diamonds$carat,y=diamonds$price,main="DIAMONDS")
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(color=color)
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors)
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())
diamonds <- read.csv("/Users/malit/Downloads/archive (1)/diamonds.csv")
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color='purple'))+scale_color_manual(values=colors())
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())++facet_grid(carat~price)
diamonds <- read.csv("/Users/malit/Downloads/archive (1)/diamonds.csv")
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())++facet_grid(carat~price)
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())+facet_grid(carat~price)

diamonds<- read.csv("/Users/malit/Downloads/archive (1)/diamonds.csv")
View(diamonds)
plot(x=diamonds$carat,y=diamonds$price,main="DIAMONDS")
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())
install.packages("ggplot2")
library(ggplot2)
install.packages("ggplot2")
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))+scale_color_manual(values=colors())
ggplot(data = diamonds,aes(x=carat, y=price))+geom_point(aes(color=color))
